services:
  renagro-etl-db:
    image: postgis/postgis:16-3.4-alpine
    container_name: renagro-etl-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: renagro
    ports:
      - "5433:5432"
    volumes:
      - ./docker/data-db:/var/lib/postgresql/data

  renagro-etl-queue:
    image: rabbitmq:4.0.7-management-alpine
    container_name: renagro-etl-queue
    ports:
      - "5672:5672"  # Puerto para AMQP (conexión de clientes)
      - "15672:15672"  # Puerto para la interfaz de gestión (management UI)
    volumes:
      - ./docker/queue/data:/var/lib/rabbitmq  # Persistencia de datos en el host
      - ./docker/queue/config:/etc/rabbitmq  # Persistencia de configuraciones en el host
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  renagro-etl-redis:
    image: redis:7.4.0-alpine
    container_name: renagro-etl-redis
    ports:
      - "6379:6379"

  renagro-etl-postgrest:
    image: postgrest/postgrest:v12.2.3
    container_name: renagro-etl-postgrest
    depends_on:
      - renagro-etl-db
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:authenticator_pass@renagro-etl-db:5432/renagro
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: ${POSTGREST_JWT_SECRET:-0478718218e466bd993b3e17344c48c5}
      PGRST_DB_MAX_ROWS: 100
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000

