ALTER TABLE "sc_renagro_mag"."boletas"
ADD COLUMN "neo_punto_no_upa" TEXT,
ADD COLUMN "neo_punto_upa" TEXT,
ADD COLUMN "neo_trazo_v1" TEXT,
ADD COLUMN "neo_trazo_v2" TEXT,
ADD COLUMN "neo_trazo_v3" TEXT,
ADD COLUMN "neo_superficie_aprox_ha_v3_cierre" TEXT,
ADD COLUMN "neo_coordenada_v3_cierre" TEXT,
ADD COLUMN "neo_trazo_v3_cierre" TEXT,
ADD COLUMN "neo_foto_v3_cierre" TEXT,